<a href="https://colab.research.google.com/github/tharun0805/ML-23ag1a66d4/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np


In [17]:
array1=np.array([1,2,3])
print(array1)

[1 2 3]


In [18]:
array2=np.array([[1,2,3,4],
                [5,6,7,8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [19]:
array3=np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]],

                  [[5,4,12],
                  [21,14,11],
                  [14,12,19]]])
print(array3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 5  4 12]
  [21 14 11]
  [14 12 19]]]


In [20]:
print(array1.size)
print(array2.size)
print(array3.size)

3
8
18


In [21]:
print(array1.data)

In [22]:
print(array2.data)

In [23]:
print(array3.data)

In [24]:
print(array1.shape)
print(array2.shape)
print(array3.shape)

(3,)
(2, 4)
(2, 3, 3)


In [25]:
print(array1.dtype)
print(array3.dtype)
print(array3.dtype)

int64
int64
int64


In [26]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
3


In [27]:
min=np.min(array1)
print(min)

1


In [28]:
max=np.max(array1)
print(max)

3


In [29]:
mean=np.mean(array1)
print(mean)

2.0


In [32]:
print(array1.itemsize)
print(array2.itemsize)
print(array3.itemsize)

8
8
8
