<a href="https://colab.research.google.com/github/tharun0805/ML-23ag1a66d4/blob/main/ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
array1=np.array([1,2,3])
print(array1)

[1 2 3]


In [ ]:
array2=np.array([[1,2,3,4],
                [5,6,7,8]])
print(array2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array3=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(array1.size)
print(array2.size)
print(array3.size)

3
8
9


In [ ]:
print(array1.data)

In [ ]:
print(array2.data)

In [ ]:
print(array3.data)

In [ ]:
print(array1.shape)
print(array2.shape)
print(array3.shape)

(3,)
(2, 4)
(3, 3)


In [ ]:
print(array1.dtype)
print(array3.dtype)
print(array3.dtype)

int64
int64
int64


In [ ]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


In [ ]:
min=np.min(array1)
print(min)

1


In [ ]:
max=np.max(array1)
print(max)

3


In [ ]:
mean=np.mean(array1)
print(mean)

2.0
